"""Initial Nowa schema"""
from alembic import op
import sqlalchemy as sa
import nowa.db


revision = '00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas')),
    sa.UniqueConstraint('name_en', name=op.f('uq_areas_name_en'))
    )
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('specialty', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('max_per_evening', sa.Integer(), nullable=True),
    sa.Column('usual_visit_min', sa.Integer(), server_default='15', nullable=False),
    sa.Column('cushion_min', sa.Integer(), server_default='10', nullable=False),
    sa.Column('safe_drive_min', sa.Integer(), server_default='45', nullable=False),
    sa.Column('secretary_alerts_on', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('sandbox_expires_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('clock_offset_s', sa.Integer(), server_default='0', nullable=False),
    sa.Column('judge_id', sa.Text(), nullable=True),
    sa.Column('demo_run_active', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.CheckConstraint('clock_offset_s = 0 OR is_sandbox', name=op.f('ck_clinics_sandbox_offset')),
    sa.CheckConstraint('cushion_min IN (5, 10, 15)', name=op.f('ck_clinics_cushion')),
    sa.CheckConstraint('max_per_evening IS NULL OR max_per_evening > 0', name=op.f('ck_clinics_positive_max')),
    sa.CheckConstraint('usual_visit_min > 0', name=op.f('ck_clinics_positive_visit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinics')),
    sa.UniqueConstraint('slug', name=op.f('uq_clinics_slug'))
    )
    op.create_table('pending_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_e164', sa.Text(), nullable=False),
    sa.Column('created_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_signups'))
    )
    op.create_table('rate_counters',
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('window_start', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('window_s', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'key_hash', 'window_start', name=op.f('pk_rate_counters'))
    )
    op.create_table('telegram_links',
    sa.Column('phone_e164', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.Text(), nullable=False),
    sa.Column('linked_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('doctor', 'patient')", name=op.f('ck_telegram_links_kind_values')),
    sa.PrimaryKeyConstraint('phone_e164', 'kind', name=op.f('pk_telegram_links'))
    )
    op.create_table('area_hour_travel',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('mean_min', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.CheckConstraint('hour BETWEEN 0 AND 23', name=op.f('ck_area_hour_travel_hour_range')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_area_hour_travel_weekday_range')),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_area_hour_travel_area_id_areas')),
    sa.PrimaryKeyConstraint('area_id', 'weekday', 'hour', name=op.f('pk_area_hour_travel'))
    )
    op.create_table('clinic_day_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('closed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.CheckConstraint('closed OR (start IS NOT NULL AND "end" IS NOT NULL)', name=op.f('ck_clinic_day_overrides_open_hours')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_clinic_day_overrides_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinic_day_overrides')),
    sa.UniqueConstraint('clinic_id', 'date', name=op.f('uq_clinic_day_overrides_clinic_id'))
    )
    op.create_index(op.f('ix_clinic_day_overrides_clinic_id'), 'clinic_day_overrides', ['clinic_id'], unique=False)
    op.create_table('clinic_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_clinic_hours_weekday_range')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_clinic_hours_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinic_hours'))
    )
    op.create_index(op.f('ix_clinic_hours_clinic_id'), 'clinic_hours', ['clinic_id'], unique=False)
    op.create_table('clinic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_clinic_info_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinic_info')),
    sa.UniqueConstraint('clinic_id', 'key', name=op.f('uq_clinic_info_clinic_id'))
    )
    op.create_index(op.f('ix_clinic_info_clinic_id'), 'clinic_info', ['clinic_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('phone_e164', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_contacts_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_clinic_id'), 'contacts', ['clinic_id'], unique=False)
    op.create_table('daily_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('booked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('came', sa.Integer(), server_default='0', nullable=False),
    sa.Column('didnt_come', sa.Integer(), server_default='0', nullable=False),
    sa.Column('walkins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancelled', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_wait_min', sa.Float(), nullable=True),
    sa.Column('avg_visit_min', sa.Float(), nullable=True),
    sa.Column('start_delay_min', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_daily_totals_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_totals')),
    sa.UniqueConstraint('clinic_id', 'date', name=op.f('uq_daily_totals_clinic_id'))
    )
    op.create_index(op.f('ix_daily_totals_clinic_id'), 'daily_totals', ['clinic_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('mobile_e164', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.CheckConstraint("lang IN ('ar', 'en', 'franco')", name=op.f('ck_doctors_lang_values')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_doctors_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors')),
    sa.UniqueConstraint('mobile_e164', name=op.f('uq_doctors_mobile_e164'))
    )
    op.create_index(op.f('ix_doctors_clinic_id'), 'doctors', ['clinic_id'], unique=False)
    op.create_table('evenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(), server_default='scheduled', nullable=False),
    sa.Column('doctor_on_way_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('doctor_eta_min', sa.Float(), nullable=True),
    sa.Column('projected_start', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(), nullable=True),
    sa.CheckConstraint("closed_by IN ('doctor', 'auto', 'system_no_taps')", name=op.f('ck_evenings_closed_by_values')),
    sa.CheckConstraint("state IN ('scheduled', 'doctor_on_way', 'running', 'closed', 'cancelled')", name=op.f('ck_evenings_state_values')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_evenings_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evenings')),
    sa.UniqueConstraint('clinic_id', 'date', name=op.f('uq_evenings_clinic_id'))
    )
    op.create_index(op.f('ix_evenings_clinic_id'), 'evenings', ['clinic_id'], unique=False)
    op.create_table('health_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('phone_key', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('trigger_text', sa.Text(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('template_version', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('commit', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('supporting_sentence', sa.Text(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('triage_emergency', 'triage_urgent', 'health_answer')", name=op.f('ck_health_record_kind_values')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_health_record_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_record'))
    )
    op.create_index(op.f('ix_health_record_clinic_id'), 'health_record', ['clinic_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_idempotency_keys_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('key', name=op.f('uq_idempotency_keys_key'))
    )
    op.create_index(op.f('ix_idempotency_keys_clinic_id'), 'idempotency_keys', ['clinic_id'], unique=False)
    op.create_table('learned_pace',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('mean_visit_min', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_learned_pace_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('clinic_id', name=op.f('pk_learned_pace'))
    )
    op.create_index(op.f('ix_learned_pace_clinic_id'), 'learned_pace', ['clinic_id'], unique=False)
    op.create_table('learned_start_gap',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('mean_min', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_learned_start_gap_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('clinic_id', name=op.f('pk_learned_start_gap'))
    )
    op.create_index(op.f('ix_learned_start_gap_clinic_id'), 'learned_start_gap', ['clinic_id'], unique=False)
    op.create_table('link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('used_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('doctor_telegram', 'patient_telegram')", name=op.f('ck_link_tokens_kind_values')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_link_tokens_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_tokens'))
    )
    op.create_index(op.f('ix_link_tokens_clinic_id'), 'link_tokens', ['clinic_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_patients_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_table('saved_answers',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('question_norm', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('saved_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_saved_answers_clinic_id_clinics')),
    sa.UniqueConstraint('clinic_id', 'question_norm', name=op.f('uq_saved_answers_clinic_id'))
    )
    op.create_index(op.f('ix_saved_answers_clinic_id'), 'saved_answers', ['clinic_id'], unique=False)
    op.create_table('secretary_links',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('used_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('telegram_chat_id', sa.Text(), nullable=True),
    sa.Column('revoked_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_secretary_links_clinic_id_clinics'))
    )
    op.create_index(op.f('ix_secretary_links_clinic_id'), 'secretary_links', ['clinic_id'], unique=False)
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('due_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('travel_check', 'leave_now_check', 'silent_check', 'are_you_on_way', 'evening_auto_close', 'evening_system_close', 'send_retry', 'delivery_timeout', 'evening_report', 'retention_daily', 'sandbox_expire', 'pending_signup_purge')", name=op.f('ck_timers_kind_values')),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'cancelled', 'failed')", name=op.f('ck_timers_status_values')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_timers_clinic_id_clinics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timers')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_timers_idempotency_key'))
    )
    op.create_index(op.f('ix_timers_clinic_id'), 'timers', ['clinic_id'], unique=False)
    op.create_index('ix_timers_status_due_at', 'timers', ['status', 'due_at'], unique=False)
    op.create_table('usage',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.CheckConstraint("service IN ('ai', 'sms', 'mapbox', 'telegram')", name=op.f('ck_usage_service_values')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_usage_clinic_id_clinics')),
    sa.UniqueConstraint('date', 'clinic_id', 'judge_id', 'service', name=op.f('uq_usage_date'))
    )
    op.create_index(op.f('ix_usage_clinic_id'), 'usage', ['clinic_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('evening_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('order_key', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('state', sa.String(), server_default='booked', nullable=False),
    sa.Column('expected_shown', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('expected_frozen', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('told_to_leave_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('on_my_way_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('travel_min', sa.Float(), nullable=True),
    sa.Column('link_code_hash', sa.Text(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('created_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('silent', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.CheckConstraint("lang IN ('ar', 'en', 'franco')", name=op.f('ck_bookings_lang_values')),
    sa.CheckConstraint("source = 'walkin_tap' OR (patient_id IS NOT NULL AND contact_id IS NOT NULL)", name=op.f('ck_bookings_booking_identity')),
    sa.CheckConstraint("source IN ('chat', 'walkin_tap')", name=op.f('ck_bookings_source_values')),
    sa.CheckConstraint("state IN ('booked', 'told_to_leave', 'on_my_way', 'seen', 'cancelled', 'didnt_come')", name=op.f('ck_bookings_state_values')),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_bookings_area_id_areas')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_bookings_clinic_id_clinics')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_bookings_contact_id_contacts')),
    sa.ForeignKeyConstraint(['evening_id'], ['evenings.id'], name=op.f('fk_bookings_evening_id_evenings')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_bookings_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('evening_id', 'queue_number', name=op.f('uq_bookings_evening_id'))
    )
    op.create_index(op.f('ix_bookings_clinic_id'), 'bookings', ['clinic_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('evening_id', sa.Integer(), nullable=False),
    sa.Column('text_norm', sa.Text(), nullable=False),
    sa.Column('text_display', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('draft_answer', sa.Text(), nullable=True),
    sa.Column('answering_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'answered', 'later', 'dismissed')", name=op.f('ck_questions_status_values')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_questions_clinic_id_clinics')),
    sa.ForeignKeyConstraint(['evening_id'], ['evenings.id'], name=op.f('fk_questions_evening_id_evenings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('clinic_id', 'evening_id', 'text_norm', name=op.f('uq_questions_clinic_id'))
    )
    op.create_index(op.f('ix_questions_clinic_id'), 'questions', ['clinic_id'], unique=False)
    op.create_table('action_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('commit', sa.Text(), nullable=False),
    sa.CheckConstraint("actor IN ('patient', 'doctor', 'secretary', 'system', 'ai')", name=op.f('ck_action_record_actor_values')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_action_record_booking_id_bookings')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_action_record_clinic_id_clinics')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_action_record_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_record'))
    )
    op.create_index(op.f('ix_action_record_clinic_id'), 'action_record', ['clinic_id'], unique=False)
    op.create_index('ix_action_record_clinic_id_at', 'action_record', ['clinic_id', 'at'], unique=False)
    op.create_table('consents',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('booking_for', sa.String(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.Text(), nullable=False),
    sa.Column('at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("booking_for IN ('self', 'other')", name=op.f('ck_consents_booking_for_values')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_consents_booking_id_bookings')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_consents_clinic_id_clinics')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_consents_contact_id_contacts'))
    )
    op.create_index(op.f('ix_consents_clinic_id'), 'consents', ['clinic_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('pending_signup_id', sa.Integer(), nullable=True),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('template_id', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('adapter', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("adapter IN ('screen_phone', 'mac_relay', 'telegram', 'we_business')", name=op.f('ck_outbox_adapter_values')),
    sa.CheckConstraint("audience IN ('patient', 'doctor', 'secretary')", name=op.f('ck_outbox_audience_values')),
    sa.CheckConstraint("channel IN ('sms', 'telegram')", name=op.f('ck_outbox_channel_values')),
    sa.CheckConstraint("lang IN ('ar', 'en', 'franco')", name=op.f('ck_outbox_lang_values')),
    sa.CheckConstraint("status IN ('queued', 'sent', 'delivered', 'failed', 'blocked_by_brake', 'blocked_unapproved')", name=op.f('ck_outbox_status_values')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_outbox_booking_id_bookings')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_outbox_clinic_id_clinics')),
    sa.ForeignKeyConstraint(['pending_signup_id'], ['pending_signups.id'], name=op.f('fk_outbox_pending_signup_id_pending_signups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_outbox_idempotency_key'))
    )
    op.create_index(op.f('ix_outbox_clinic_id'), 'outbox', ['clinic_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('evening_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('started_at', nowa.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', nowa.db.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_visits_booking_id_bookings')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_visits_clinic_id_clinics')),
    sa.ForeignKeyConstraint(['evening_id'], ['evenings.id'], name=op.f('fk_visits_evening_id_evenings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits'))
    )
    op.create_index(op.f('ix_visits_clinic_id'), 'visits', ['clinic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_clinic_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_outbox_clinic_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_consents_clinic_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index('ix_action_record_clinic_id_at', table_name='action_record')
    op.drop_index(op.f('ix_action_record_clinic_id'), table_name='action_record')
    op.drop_table('action_record')
    op.drop_index(op.f('ix_questions_clinic_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_bookings_clinic_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_usage_clinic_id'), table_name='usage')
    op.drop_table('usage')
    op.drop_index('ix_timers_status_due_at', table_name='timers')
    op.drop_index(op.f('ix_timers_clinic_id'), table_name='timers')
    op.drop_table('timers')
    op.drop_index(op.f('ix_secretary_links_clinic_id'), table_name='secretary_links')
    op.drop_table('secretary_links')
    op.drop_index(op.f('ix_saved_answers_clinic_id'), table_name='saved_answers')
    op.drop_table('saved_answers')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_link_tokens_clinic_id'), table_name='link_tokens')
    op.drop_table('link_tokens')
    op.drop_index(op.f('ix_learned_start_gap_clinic_id'), table_name='learned_start_gap')
    op.drop_table('learned_start_gap')
    op.drop_index(op.f('ix_learned_pace_clinic_id'), table_name='learned_pace')
    op.drop_table('learned_pace')
    op.drop_index(op.f('ix_idempotency_keys_clinic_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_health_record_clinic_id'), table_name='health_record')
    op.drop_table('health_record')
    op.drop_index(op.f('ix_evenings_clinic_id'), table_name='evenings')
    op.drop_table('evenings')
    op.drop_index(op.f('ix_doctors_clinic_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_daily_totals_clinic_id'), table_name='daily_totals')
    op.drop_table('daily_totals')
    op.drop_index(op.f('ix_contacts_clinic_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_clinic_info_clinic_id'), table_name='clinic_info')
    op.drop_table('clinic_info')
    op.drop_index(op.f('ix_clinic_hours_clinic_id'), table_name='clinic_hours')
    op.drop_table('clinic_hours')
    op.drop_index(op.f('ix_clinic_day_overrides_clinic_id'), table_name='clinic_day_overrides')
    op.drop_table('clinic_day_overrides')
    op.drop_table('area_hour_travel')
    op.drop_table('telegram_links')
    op.drop_table('rate_counters')
    op.drop_table('pending_signups')
    op.drop_table('clinics')
    op.drop_table('areas')
    # ### end Alembic commands ###
